# Generated by Django 5.0.1 on 2024-01-12 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articleapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='email',
            field=models.EmailField(default=None, max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='signup',
            name='password',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='signup',
            name='username',
            field=models.CharField(default=None, max_length=30, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='signup',
            name='date_of_birth',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
